name = "Waves.jl"
uuid = "3aeb90b2-c279-43b5-a838-e72c1cae32b3"
authors = ["Rahul Manavalan <rahul.manavalan@tum.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
