name = "Waves"
uuid = "3aeb90b2-c279-43b5-a838-e72c1cae32b3"
authors = ["Rahul Manavalan <rahul.manavalan@tum.de> and contributors"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
